# Numpay Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]   

In [6]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)   # Creates numbers in a range (start,stop,step) 
                  # The stop value is NOT included, The start Value included

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)       # Creates an array fiiled with 0s.

array([0., 0., 0.])

In [11]:
np.zeros((5,5))     # Creates an matrix fiiled with 0s.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(5)        # Creates an array fiiled with 1s.

array([1., 1., 1., 1., 1.])

In [13]:
np.linspace(0,10,22)  # Creates evenly spaced numbers between two values.
                      # (Start,End,number of values)

array([ 0.        ,  0.47619048,  0.95238095,  1.42857143,  1.9047619 ,
        2.38095238,  2.85714286,  3.33333333,  3.80952381,  4.28571429,
        4.76190476,  5.23809524,  5.71428571,  6.19047619,  6.66666667,
        7.14285714,  7.61904762,  8.0952381 ,  8.57142857,  9.04761905,
        9.52380952, 10.        ])

In [14]:
np.random.rand(2,3)   #Random numbers between 0 and 1.

array([[0.92231509, 0.92518797, 0.29808752],
       [0.22710464, 0.98673361, 0.24207826]])

In [15]:
np.random.randn(3,1)   # Random numbers from normal distribution (mean=0, std=1).

array([[ 0.57218339],
       [-1.09552296],
       [ 1.79914811]])

In [16]:
a = np.random.randint(0,100,8)   # Random integers in a range.
a                                # (Low,High,size)

array([66, 28, 13, 33, 29, 91, 93, 66], dtype=int32)

In [17]:
# Find maximum or minimum value. We use max and min functions.
# Return index of max/min value. We use argmax,argmin function

In [18]:
a.max() 

np.int32(93)

In [19]:
a.min()

np.int32(13)

In [20]:
a.argmax()

np.int64(6)

In [21]:
a.argmin()

np.int64(2)

In [22]:
a.dtype

dtype('int32')

In [23]:
a = np.array([[1,2,3],[4,5,6]])    # Gives dimensions of array.

In [24]:
a.shape

(2, 3)